Repository ProjectTeam-5959/BookstoreApp, pull requests merged in 2025-10, with the labels that each got.

#38 [Review] - 기능개선 쿼리 리펙토링
  src/main/java/org/example/bookstoreapp/domain/book/controller/BookController.java
  src/main/java/org/example/bookstoreapp/domain/book/dto/BookCreateRequest.java
  src/main/java/org/example/bookstoreapp/domain/book/dto/BookUpdateRequest.java
  src/main/java/org/example/bookstoreapp/domain/book/repository/BookRepository.java
  src/main/java/org/example/bookstoreapp/domain/book/service/BookService.java
  src/main/java/org/example/bookstoreapp/domain/bookcontributor/dto/BookContributorRequest.java
  src/main/java/org/example/bookstoreapp/domain/contributor/dto/ContributorCreateRequest.java
  src/main/java/org/example/bookstoreapp/domain/review/controller/ReviewController.java
  src/main/java/org/example/bookstoreapp/domain/review/repository/CustomReviewRepository.java
  src/main/java/org/example/bookstoreapp/domain/review/repository/ReviewRepository.java
  src/main/java/org/example/bookstoreapp/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/org/example/bookstoreapp/domain/review/service/ReviewService.java
Labels: ⚡️refactor

#39 [auth] : jwt 버전 업그레이드, 유저 테이블 인덱스 추가
  build.gradle
  src/main/java/org/example/bookstoreapp/common/security/CustomAccessDeniedHandler.java
  src/main/java/org/example/bookstoreapp/common/security/JwtUtil.java
  src/main/java/org/example/bookstoreapp/common/security/SecurityConfig.java
  src/main/java/org/example/bookstoreapp/domain/user/controller/UserAdminController.java
  src/main/java/org/example/bookstoreapp/domain/user/entity/User.java
  src/test/java/org/example/bookstoreapp/config/TestSecurityConfig.java
  src/test/java/org/example/bookstoreapp/domain/auth/AuthServiceTest.java
  src/test/java/org/example/bookstoreapp/security/AuthIntegrationTest.java
  src/test/java/org/example/bookstoreapp/security/JwtUtilTest.java
Labels: 💻feat, clean

#43 docs : 리드미 추가
  README.md
Labels: 📄docs

#44 docs : README 수정
  README.md
Labels: 📄docs
