Repository ProjectTeam-5959/BookstoreApp, pull requests merged in 2025-09, with the labels that each got.

#5 [review] feat : 3-layer 아키텍처 기반 패키지 구조 및 기본 엔티티/레포지토리 추가
  src/main/java/org/example/bookstoreapp/review/controller/ReviewController.java
  src/main/java/org/example/bookstoreapp/review/dto/request/ReviewRequest.java
  src/main/java/org/example/bookstoreapp/review/dto/response/ReviewResponse.java
  src/main/java/org/example/bookstoreapp/review/entity/Review.java
  src/main/java/org/example/bookstoreapp/review/repository/ReviewRepository.java
  src/main/java/org/example/bookstoreapp/review/service/ReviewService.java
Labels: 💻feat

#6 [도서, 작가] 엔티티 및 레포지토리 기본설정
  src/main/java/org/example/bookstoreapp/domain/author/entity/Author.java
  src/main/java/org/example/bookstoreapp/domain/author/repository/AuthorRepository.java
  src/main/java/org/example/bookstoreapp/domain/book/entity/Book.java
  src/main/java/org/example/bookstoreapp/domain/book/entity/ContributorRole.java
  src/main/java/org/example/bookstoreapp/domain/book/repository/BookRepository.java
  src/main/java/org/example/bookstoreapp/domain/bookauthor/entity/BookAuthor.java
  src/main/java/org/example/bookstoreapp/domain/bookauthor/repository/BookAuthorRepository.java
Labels: 💻feat

#7 [all] feat: api 기본 경로 추가
  src/main/resources/application.yml
Labels: 💻feat

#10 [BusinessException] feat: ErrorCode 적용 및 예외 처리 구조 개선
  src/main/java/org/example/bookstoreapp/common/exception/BusinessException.java
  src/main/java/org/example/bookstoreapp/common/exception/ErrorCode.java
  src/main/java/org/example/bookstoreapp/common/exception/GlobalExceptionHandler.java
Labels: 💻feat

#13 [all] feat: 매직 넘버 대신 HTTP code 활용으로 변경
  src/main/java/org/example/bookstoreapp/common/exception/BusinessException.java
  src/main/java/org/example/bookstoreapp/common/exception/ErrorCode.java
  src/main/java/org/example/bookstoreapp/common/exception/GlobalExceptionHandler.java
Labels: 💻feat

#21 [Auth/User] 테스트 시 Mock AuthUser 어노테이션 도입 등
  build.gradle
  src/main/java/org/example/bookstoreapp/common/config/CustomAccessDeniedHandler.java
  src/main/java/org/example/bookstoreapp/common/config/SecurityConfig.java
  src/main/java/org/example/bookstoreapp/domain/auth/controller/AuthController.java
  src/main/java/org/example/bookstoreapp/domain/auth/dto/request/SigninRequest.java
  src/main/java/org/example/bookstoreapp/domain/auth/dto/request/SignupRequest.java
  src/main/java/org/example/bookstoreapp/domain/auth/exception/AuthErrorCode.java
  src/main/java/org/example/bookstoreapp/domain/auth/service/AuthService.java
  src/main/java/org/example/bookstoreapp/domain/user/dto/request/UserChangeNameAndPasswordRequest.java
  src/main/java/org/example/bookstoreapp/domain/user/service/UserService.java
  src/main/resources/application-test.yml
  src/test/java/org/example/bookstoreapp/config/WithMockAuthUser.java
  src/test/java/org/example/bookstoreapp/config/WithMockUserSecurityContextFactory.java
  src/test/java/org/example/bookstoreapp/domain/auth/AuthServiceTest.java
  src/test/java/org/example/bookstoreapp/domain/user/UserServiceTest.java
Labels: 💻feat, 🛠️fix, ⚡️refactor

#27 [auth] 토큰 인증문제 해결 + request 필드 검증요건 미충족 시 예외처리 등
  src/main/java/org/example/bookstoreapp/common/config/CustomAccessDeniedHandler.java
  src/main/java/org/example/bookstoreapp/common/config/JwtUtil.java
  src/main/java/org/example/bookstoreapp/common/exception/GlobalExceptionHandler.java
  src/main/java/org/example/bookstoreapp/domain/auth/controller/AuthController.java
  src/main/java/org/example/bookstoreapp/domain/auth/dto/request/SigninRequest.java
  src/main/java/org/example/bookstoreapp/domain/auth/dto/request/SignupRequest.java
  src/main/java/org/example/bookstoreapp/domain/auth/exception/AuthErrorCode.java
  src/main/java/org/example/bookstoreapp/domain/user/controller/UserController.java
  src/main/java/org/example/bookstoreapp/domain/user/service/UserService.java
  src/test/java/org/example/bookstoreapp/domain/auth/AuthServiceTest.java
  src/test/java/org/example/bookstoreapp/domain/user/UserAdminServiceTest.java
  src/test/java/org/example/bookstoreapp/domain/user/UserServiceTest.java
Labels: 🐞bug, 💻feat, 🛠️fix, ⚡️refactor

#29 [Review] 공통 응답 추가 및 서비스 단위 테스트 코드 작성
  src/main/java/org/example/bookstoreapp/domain/review/controller/ReviewController.java
  src/main/java/org/example/bookstoreapp/domain/review/service/ReviewService.java
  src/test/java/org/example/bookstoreapp/domain/review/ReviewServiceTest.java
Labels: 💻feat

#34 [BOOK] 도서 조회(bookResponse반환), 도서 수정
  src/main/java/org/example/bookstoreapp/domain/book/controller/BookController.java
  src/main/java/org/example/bookstoreapp/domain/book/dto/BookCreateRequest.java
  src/main/java/org/example/bookstoreapp/domain/book/dto/BookUpdateRequest.java
  src/main/java/org/example/bookstoreapp/domain/book/exception/BookErrorCode.java
  src/main/java/org/example/bookstoreapp/domain/book/service/BookServiceImpl.java
Labels: 🛠️fix, ⚡️refactor

#35 [auth/user] authService, userService 유닛 테스트 / Security 통합 테스트
  build.gradle
  src/main/java/org/example/bookstoreapp/common/security/JwtAuthenticationFilter.java
  src/main/java/org/example/bookstoreapp/common/security/JwtAuthenticationToken.java
  src/main/java/org/example/bookstoreapp/common/security/JwtUtil.java
  src/main/java/org/example/bookstoreapp/common/security/SecurityConfig.java
  src/main/java/org/example/bookstoreapp/domain/auth/service/AuthService.java
  src/main/java/org/example/bookstoreapp/domain/user/controller/UserAdminController.java
  src/main/java/org/example/bookstoreapp/domain/user/dto/request/UserChangeNameAndPasswordRequest.java
  src/main/java/org/example/bookstoreapp/domain/user/dto/request/UserRoleChangeRequest.java
  src/main/resources/application-test.yml
  src/test/java/org/example/bookstoreapp/config/TestSecurityConfig.java
  src/test/java/org/example/bookstoreapp/config/WithMockUserSecurityContextFactory.java
  src/test/java/org/example/bookstoreapp/domain/auth/AuthServiceTest.java
  src/test/java/org/example/bookstoreapp/domain/user/UserAdminServiceTest.java
  src/test/java/org/example/bookstoreapp/domain/user/UserServiceTest.java
  src/test/java/org/example/bookstoreapp/security/AuthIntegrationTest.java
  src/test/java/org/example/bookstoreapp/security/JwtUtilTest.java
  src/test/resources/application-test.yml
Labels: 💻feat, 🛠️fix, ⚡️refactor

#36 [Bookservice] 인터페이스-구현체 관계 해제(팀 컨벤션에 맞춰 수정)
  src/main/java/org/example/bookstoreapp/domain/book/service/BookService.java
  src/main/java/org/example/bookstoreapp/domain/book/service/BookServiceImpl.java
Labels: ✨style, 🛠️fix, ⚡️refactor
